#!/usr/bin/env python3
from pathlib import Path

MODULES = {
"GLOBAL": ["Splash","Login","Create account","Password recovery","Farm membership selector","Create farm wizard","Join invited farm","First-run species setup","Role and permissions explanation","Notification permission","Camera permission","Bluetooth permission","Location permission","Offline-first introduction","Terms and privacy","Session expired","Farm access revoked","Backend unavailable","Account profile","Sign-out confirmation"],
"HOME": ["Farm Home","Species Navigator","Today Summary","Farm Alerts Centre","Farm Activity Stream","Global Search","Search Results","Quick Capture Launcher","Sync Status Centre entry","Farm Switcher","Notification Centre","Role-tailored Home"],
"GOAT": ["Goat Dashboard","Herd List","Goat Profile","Register Goat","Edit Goat Identity","Goat Search","RFID or Tag Scan","Goat Photo or Gallery","Goat Timeline","Goat Documents","Weight Capture","BLE Scale Pairing","Growth History","Growth Chart","ADG Detail","Body Condition Score","Milk Capture","Lactation Dashboard","Lactation History","SCC Capture","SCC History","FAMACHA Capture","FAMACHA Reference","FAMACHA History","Goat Health Summary","Goat Treatment History","Goat Withdrawal Status","Goat Vet Visit","Goat Lab Result","Doe Reproduction Dashboard","Heat Record","Mating or Service","Sire Selector","Pregnancy Check","Pregnancy Dashboard","Kidding Due","Record Kidding","Kidding Event Detail","Register Kid","Kid Cohort","Kid Profile","Weaning","Lactation Plan","Pedigree Tree","Parentage Editor","Breeding Candidate Compare","Goat Groups","Group Membership","Goat Movement","Official Identifier","Status Change","Sale Exit","Mortality Record","Cull Record","Goat Report"],
"RABBIT": ["Rabbitry Dashboard","Breeding Animals","Doe Profile","Buck Profile","Rabbit Registration","Cage Dashboard","Cage Detail","Cage Occupancy","Breeding Wave","Mating","Palpation","Pregnancy Status","Nest-Box Schedule","Nest Placement","Nest Removal","Kindling Due","Record Kindling","Litter Profile","Kit Census","Foster Kits","Kit Mortality","Weaning","Individualise Kits","Retention Selection","Replacement Candidate Compare","Market Plan","Customer Waitlist","Reservation","Contract","Sale Allocation","Rabbit Pedigree","Rabbit Weight","Rabbit Health","GI Stasis Red-Flag","Rabbit Timeline","Rabbit Report"],
"SHEEP": ["Sheep Dashboard","Mob or Flock List","Sheep Profile","Sheep Registration","EID Scan","Weight Capture","Growth History","BCS","FAMACHA","Joining Dashboard","Record Joining","Pregnancy Scan","Lambing Due","Record Lambing","Lamb Profile","Lamb Marking","Weaning","Wool Dashboard","Shearing","Fleece Record","Micron or Fibre Result","Dag Score","Footrot","Flystrike","Health Summary","Pedigree","Movement","Paddock Assignment","Official Identifier","Status Change","Timeline","Sheep Report"],
"CATTLE": ["Cattle Dashboard","Herd or Mob or Lot List","Cattle Profile","Cattle Registration","EID or Official Identifier","Weight Capture","Growth History","BCS","Heat Detection","Service","AI Record","ET Record","Pregnancy Diagnosis","Calving Due","Record Calving","Calf Registration","Weaning","Dairy Dashboard","Milk Capture","Lactation History","SCC Capture","SCC History","Locomotion Score","Dry-Off","Beef Dashboard","Feedlot Placement","Feedlot Lot Detail","Days on Feed","Lot Close-Out","Movement","Official Movement Record","Pedigree","Health Summary","Status Change","Timeline","Cattle Report"],
"POULTRY": ["Poultry Dashboard","Enabled Poultry Kinds","Enable Kind","Flock List","Flock Profile","House List","House Detail","Placement","Daily Mortality","Egg Production","Egg Collection","Feed or FCR","Vaccination Schedule","Vaccination Capture","Biosecurity Dashboard","Biosecurity Check","Hatchery Dashboard","Eggs Set","Incubation Batch","Candling","Hatch Result","Chick Placement","Flock Move","Flock Close-Out","Poultry Health","Flock Timeline","Poultry Report"],
"HEALTH": ["Health Dashboard","Today Health Actions","Observation List","Record Observation","Health Case Detail","Treatment List","Record Treatment","Treatment Detail","Withdrawal Dashboard","Withdrawal Detail","Vaccination Schedule","Vaccination Capture","Formulary","Formulary Item","Protocol Packs","Protocol Pack Detail","Accept Protocol Pack","Apply Protocol Pack","Protocol Slot Editor","Vet Visit List","Record Vet Visit","Vet Visit Detail","Lab Results","Record Lab Result","Lab Result Detail","Disease or Reference Library","Reference Detail","Emergency or Red Flag","Health Timeline","Health Report"],
"TASK": ["Today Board","All Tasks","Task Detail","Create Task","Edit Task","Assigned to Me","Scheduled","Overdue","Completed","Calendar","Recurrence","Task Attachment","Task Completion Evidence","Task Generated by Protocol","Task Generated by Lifecycle"],
"INV": ["Inventory Dashboard","Inventory List","Inventory Item","Create Item","Receive Stock","Receive Lot","Issue Stock","FEFO Issue","Lot Detail","Expiry Queue","Low Stock","Reorder Rules","Reorder Alert","Stock Movement History","Stock Adjustment","Stock Count","Inventory Search","Supplier Binding","Inventory Report"],
"FEED": ["Feed Dashboard","Feed Inventory","Feed Item","Feed Plan","Feeding Schedule","Feed Issue or Consumption","Feed Cost","Ration Builder","Ration Analysis","Ration Compare","Feed Alert","Feed Report"],
"WATER": ["Water Dashboard","Water Point List","Water Point Detail","Consumption Capture","Water Inspection","Water Quality Result","Water Issue","Water Maintenance","Water History","Water Report"],
"PASTURE": ["Pasture Dashboard","Paddock List","Paddock Detail","Grazing Rotation","Group Movement","Rest Period","Carrying Capacity","Pasture Condition","Grazing History","Pasture Map","Pasture Report"],
"GROUP": ["Groups","Group Detail","Create Group","Edit Group","Membership","Group Census","Group Move","Group Health","Group Timeline"],
"LABOUR": ["Labour Dashboard","Worker List","Worker Detail","Worker Assignment","Work Log","Attendance or Availability","Labour Cost","Coverage or Workload","Labour Report"],
"ASSET": ["Assets Dashboard","Asset Register","Asset Detail","Create Asset","Meter or Usage Capture","Maintenance Schedule","Maintenance Job","Breakdown","Service History","Asset Documents","Asset Photo Gallery","Asset Report"],
"FIN": ["Finance Dashboard","Transactions","Transaction Detail","Record Income","Record Expense","Enterprise Profitability","Species Cost","Activity Cost","Cash Flow","Budget","Variance","Finance Report","Export"],
"SALES": ["Sales Dashboard","Customer List","Customer Detail","Sales Orders","Sale Detail","Create Sale","Animal Sale","Produce Sale","Rabbit Reservation Sale","Delivery or Collection","Sales History","Sales Report"],
"PROC": ["Procurement Dashboard","Supplier List","Supplier Detail","Purchase Orders","Purchase Detail","Create Purchase","Receive Purchase","Purchase to Inventory","Procurement History","Procurement Report"],
"CAP": ["Capacity Dashboard","Housing Capacity","Stocking Pressure","Cage Capacity","Poultry House Capacity","Paddock Capacity","Feed Capacity","Water Capacity","Capacity Forecast","Capacity Alert"],
"GEN": ["Genetics Dashboard","Pedigree Explorer","Parentage Record","Parentage Verification","Relationship Explorer","COI Analysis","Mate Comparison","Candidate Ranking","Genetic Warning","Genetics Report"],
"AN": ["Farm Analytics","Species Performance","Reproduction Analytics","Growth Analytics","Mortality Analytics","Health Trends","Production Analytics","Feed Efficiency","Financial Performance","Benchmark or Compare","Anomaly Centre","Forecasts","Insight Detail","Evidence or Source Drilldown"],
"SIM": ["Simulation Hub","Herd Growth Scenario","Breeding Scenario","Feed Scenario","Capacity Scenario","Financial Scenario","Scenario Compare","Scenario Save","Scenario Report"],
"SEARCH": ["Search Home","Search Results","Filter Sheet","No Results","Offline Local Search","Server Search Unavailable","RFID Result","QR or Barcode Result","Recent Searches"],
"AI": ["Copilot Home","Ask Farm OS","Conversation","Insight Detail","Evidence or Sources","Suggested Actions","Action Review","Anomaly Review","Model Provider Settings","API Key or Provider Connection","AI Privacy and Controls","AI Unavailable"],
"REPORT": ["Reports Hub","Animal Report","Herd or Flock Report","Health Report","Production Report","Finance Report","Inventory Report","Breeding Report","Genetics Report","Operations Report","Export Sheet","Generated Documents","Document Viewer","Share or Print","Certificate Viewer"],
"ADMIN": ["Settings Home","Farm Profile","Members","Invite Member","Role Detail","Permissions","Species Configuration","Poultry Kinds","Locations","Units","Currency","Notifications","Offline or Sync Settings","Search Settings","Integrations","Hardware","BLE Devices","RFID Devices","Model API","Security","Session or Devices","Data Export","Backup or Restore Status","Audit Log","About or Version"],
"SYNC": ["Offline Banner","Sync Status","Pending Changes","In-Flight","Retry Waiting","Conflict Centre","Conflict Detail","Rejected Mutation","Dead Letter","Auth Required","Farm Access Revoked","Backend Outage","Search Outage","Local Data Safe Confirmation","Manual Sync","Last Successful Sync","Reconciliation Detail","Mutation Trace"],
"ATOM": ["Date Picker","Time Picker","Species Selector","Animal Selector","Group Selector","Farm Selector","Location Selector","Sire or Dam Selector","Inventory Item Selector","Lot Selector","Supplier Selector","Customer Selector","Worker Selector","Asset Selector","Photo Capture","Attachment Picker","Document Picker","QR or Barcode Scanner","RFID Scanner","BLE Device Picker","Filter Sheet","Sort Sheet","Bulk Selection","Bulk Action Sheet","Delete Confirmation","Irreversible Status Confirmation","Conflict Resolution Sheet","Permission Explanation","Export Format","Share Sheet","Search Empty State","Loading Skeleton","Error Recovery","Offline Save Receipt","Sync Pending Receipt"],
}

I1 = {"FOS-GLOBAL-001","FOS-GLOBAL-002","FOS-GLOBAL-003","FOS-GLOBAL-006","FOS-GLOBAL-007","FOS-GLOBAL-014"}
I2 = {
"FOS-GLOBAL-005","FOS-GLOBAL-008","FOS-HOME-001","FOS-HOME-002","FOS-HOME-003","FOS-HOME-008",
"FOS-GOAT-001","FOS-GOAT-003","FOS-GOAT-018","FOS-GOAT-025","FOS-GOAT-030","FOS-GOAT-035","FOS-GOAT-036","FOS-GOAT-040","FOS-GOAT-041","FOS-GOAT-044",
"FOS-RABBIT-001","FOS-RABBIT-003","FOS-RABBIT-004","FOS-RABBIT-006","FOS-RABBIT-009","FOS-RABBIT-013","FOS-RABBIT-016","FOS-RABBIT-018","FOS-RABBIT-026","FOS-RABBIT-031",
"FOS-SHEEP-001","FOS-SHEEP-003","FOS-SHEEP-010","FOS-SHEEP-013","FOS-SHEEP-015","FOS-SHEEP-018","FOS-SHEEP-026",
"FOS-CATTLE-001","FOS-CATTLE-003","FOS-CATTLE-014","FOS-CATTLE-018","FOS-CATTLE-025","FOS-CATTLE-032",
"FOS-POULTRY-001","FOS-POULTRY-002","FOS-POULTRY-005","FOS-POULTRY-007","FOS-POULTRY-015","FOS-POULTRY-017",
"FOS-HEALTH-001","FOS-HEALTH-002","FOS-TASK-001","FOS-INV-001","FOS-FEED-001","FOS-FEED-004","FOS-WATER-001","FOS-WATER-003","FOS-PASTURE-001","FOS-PASTURE-003","FOS-PASTURE-004","FOS-PASTURE-010","FOS-LABOUR-001","FOS-ASSET-001","FOS-ASSET-003","FOS-FIN-001","FOS-FIN-006","FOS-SALES-001","FOS-PROC-001","FOS-CAP-001","FOS-GEN-001","FOS-GEN-002","FOS-AN-001","FOS-AN-002","FOS-SIM-001","FOS-SEARCH-001","FOS-AI-001","FOS-AI-002","FOS-REPORT-001",
}
I4 = {
"FOS-GLOBAL-016","FOS-GLOBAL-017","FOS-GLOBAL-018","FOS-GLOBAL-020",
"FOS-HOME-004","FOS-GOAT-020","FOS-GOAT-027","FOS-GOAT-028","FOS-GOAT-029","FOS-GOAT-037","FOS-GOAT-051","FOS-GOAT-052","FOS-GOAT-053","FOS-GOAT-054",
"FOS-RABBIT-017","FOS-RABBIT-021","FOS-RABBIT-033","FOS-RABBIT-034","FOS-SHEEP-009","FOS-SHEEP-014","FOS-SHEEP-023","FOS-SHEEP-024","FOS-SHEEP-030","FOS-CATTLE-015","FOS-CATTLE-021","FOS-CATTLE-023","FOS-CATTLE-033","FOS-CATTLE-034","FOS-POULTRY-009","FOS-POULTRY-014","FOS-POULTRY-015","FOS-POULTRY-016","FOS-POULTRY-025",
"FOS-HEALTH-005","FOS-HEALTH-007","FOS-HEALTH-008","FOS-HEALTH-009","FOS-HEALTH-010","FOS-HEALTH-012","FOS-HEALTH-017","FOS-HEALTH-018","FOS-HEALTH-021","FOS-HEALTH-024","FOS-HEALTH-028","FOS-TASK-008","FOS-INV-008","FOS-INV-010","FOS-INV-011","FOS-INV-015","FOS-FEED-011","FOS-WATER-006","FOS-WATER-007","FOS-ASSET-008","FOS-SALES-007","FOS-CAP-010","FOS-GEN-009","FOS-AN-005","FOS-AN-011","FOS-AI-007","FOS-AI-008","FOS-AI-010","FOS-ADMIN-020","FOS-ADMIN-021",
"FOS-SYNC-006","FOS-SYNC-007","FOS-SYNC-008","FOS-SYNC-009","FOS-SYNC-010","FOS-SYNC-011","FOS-SYNC-012","FOS-SYNC-013",
"FOS-ATOM-025","FOS-ATOM-026","FOS-ATOM-027",
}

IMPLEMENTED = {
"FOS-GLOBAL-001","FOS-GLOBAL-002","FOS-GLOBAL-005","FOS-GLOBAL-006","FOS-GLOBAL-018","FOS-HOME-001","FOS-HOME-002",
"FOS-GOAT-001","FOS-GOAT-002","FOS-GOAT-003","FOS-GOAT-004","FOS-GOAT-006","FOS-GOAT-011","FOS-GOAT-016","FOS-GOAT-017","FOS-GOAT-020","FOS-GOAT-022","FOS-GOAT-031","FOS-GOAT-032","FOS-GOAT-034","FOS-GOAT-037","FOS-GOAT-039","FOS-GOAT-043","FOS-GOAT-051",
"FOS-TASK-001","FOS-TASK-004","FOS-TASK-007","FOS-TASK-008","FOS-TASK-009",
"FOS-HEALTH-001","FOS-HEALTH-003","FOS-HEALTH-004","FOS-HEALTH-007","FOS-HEALTH-009","FOS-HEALTH-013","FOS-HEALTH-015","FOS-HEALTH-017","FOS-HEALTH-018","FOS-HEALTH-019","FOS-HEALTH-021","FOS-HEALTH-024","FOS-HEALTH-026",
"FOS-INV-001","FOS-INV-002","FOS-INV-004","FOS-INV-005","FOS-INV-006","FOS-INV-007","FOS-INV-008","FOS-INV-012","FOS-INV-013",
"FOS-FIN-001","FOS-FIN-002","FOS-FIN-004","FOS-FIN-005",
"FOS-GROUP-001","FOS-PASTURE-001","FOS-LABOUR-001","FOS-ASSET-001","FOS-FEED-001","FOS-WATER-001","FOS-RABBIT-027","FOS-PROC-001","FOS-SALES-001",
"FOS-SYNC-002","FOS-SYNC-003",
}

PREFIX = {k: k for k in MODULES}

def screen_id(module: str, index: int) -> str:
    return f"FOS-{PREFIX[module]}-{index:03d}"

def visual_class(sid: str) -> str:
    if sid in I4: return "I4"
    if sid in I1: return "I1"
    if sid in I2: return "I2"
    return "I3"

lines = [
"schema_version: 2",
"source: FARM_OS_QUANTUM_COMPLETE_SCREEN_FEATURE_VISUAL_MAPPING_REV2.md",
"authority: docs/ux/FARM_OS_VISUAL_AUTHORITY.md",
"state_profile: GLOBAL_16_PLUS_STATE_MATRIX",
"role_profile: OWNER_MANAGER_SUPERVISOR_WORKER_VET_FINANCE_READONLY_ADMIN",
"device_profile: PHONE_PLUS_TABLET_WHERE_APPLICABLE",
"certification_law: VISUAL_GREEN_requires_reference_goldens_states_accessibility_drift_review_and_approval",
"screens:",
]
count = 0
for module, names in MODULES.items():
    for i, name in enumerate(names, 1):
        sid = screen_id(module, i)
        implemented = sid in IMPLEMENTED
        lines += [
            f"  - screen_id: {sid}",
            f"    name: {name}",
            f"    module: {module.lower()}",
            f"    visual_class: {visual_class(sid)}",
            f"    implementation_audit: {'VISUAL_IMPLEMENTED' if implemented else 'AUDIT_REQUIRED'}",
            "    visual_green: false",
            "    feature_green: false",
            "    required_states: GLOBAL_16_PLUS_STATE_MATRIX",
            "    required_roles: ROLE_MATRIX_APPLIES",
            "    required_devices: DEVICE_MATRIX_APPLIES",
        ]
        count += 1
lines += ["", f"screen_count: {count}", "visual_green_count: 0", "feature_green_claims_from_this_registry: 0", ""]
Path("docs/ux/FARM_OS_SCREEN_REGISTRY.yaml").write_text("\n".join(lines), encoding="utf-8")
print(f"generated {count} atomic screen records")
